apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  event-bus
  template:
    metadata:
      labels:
        app:  event-bus
    spec:
      containers: 
        - name: event-bus
          # imagePullPolicy: Always
          # image:  mernstack.azurecr.io/event-bus
          image: docker.io/mnythedocker/event-bus
          # image:  docker.io/library/event-bus:latest
          # image:  event-bus:latest

# to get errors kubectl describe pod event-bus-depl-5b5ffdddc8-xdhrg
# with "---" we can create new yml to create object
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app:  event-bus
  # type: it is default behaveior so excluded
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005 

# $ kubectl get services
# NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
# event-bus-srv   ClusterIP   10.108.115.184   <none>        4005/TCP   10s
# kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP    166m

# $ kubectl get deployments
# NAME             READY   UP-TO-DATE   AVAILABLE   AGE
# event-bus-depl   1/1     1            1           71m
# posts-depl       1/1     1            1           50m

# to rollout new image to pods
# $ kubectl rollout restart deployment  event-bus-depl
# deployment.apps/event-bus-depl restarted
